export const ADD_PRODUCTS_REQUEST = 'ADD_PRODUCTS_REQUEST';
export const ADD_PRODUCTS_SUCCESS = 'ADD_PRODUCTS_SUCCESS';

export const ADD_PRODUCT_AFTER_DELETE = 'ADD_PRODUCT_AFTER_DELETE';

export const GET_SEARCH_PRODUCT = 'GET_SEARCH_PRODUCT';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';

export const SORT_PRODUCT_BY_FIELDNAME = 'SORT_PRODUCT_BY_FIELDNAME';
